# Generated by Django 5.1.4 on 2024-12-21 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prof', '0004_post_description_en_post_description_ru_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='postlike',
            constraint=models.UniqueConstraint(fields=('user', 'post'), name='unique_user_post_like'),
        ),
    ]
