# Generated by Django 5.1.4 on 2024-12-23 04:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prof', '0008_rename_save_saveitem_items_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='saveitem',
            old_name='save_items',
            new_name='post',
        ),
        migrations.RenameField(
            model_name='saveitem',
            old_name='items',
            new_name='save',
        ),
    ]
