# Generated by Django 5.1.4 on 2024-12-24 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prof', '0009_rename_save_items_saveitem_post_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='save',
            old_name='user',
            new_name='save_user',
        ),
        migrations.RenameField(
            model_name='saveitem',
            old_name='post',
            new_name='post_item',
        ),
        migrations.RenameField(
            model_name='saveitem',
            old_name='save',
            new_name='save_item',
        ),
    ]
