# Generated by Django 5.1.4 on 2024-12-24 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prof', '0010_rename_user_save_save_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commentlike',
            old_name='comment',
            new_name='comment_like',
        ),
        migrations.AlterUniqueTogether(
            name='commentlike',
            unique_together={('user', 'comment_like')},
        ),
    ]
